# Copyright (C) 2022 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  serviceName: pgadmin
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - image: dpage/pgadmin4:6.10
          name: pgadmin
          envFrom:
            - configMapRef:
                name: pgadmin-env
          env:
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: password
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-pgadmin-volume
            - mountPath: /var/lib/pgadmin4
              name: pgadmin-pgadmin4-volume
      volumes:
        - name: pgadmin-pgadmin-volume
          persistentVolumeClaim:
            claimName: pgadmin-pgadmin-volume-pgadmin-0
        - name: pgadmin-pgadmin-volume4
          persistentVolumeClaim:
            claimName: pgadmin-pgadmin4-volume-pgadmin-0
  volumeClaimTemplates:
    - metadata:
        name: pgadmin-pgadmin-volume
        labels:
          app: pgadmin-pgadmin
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Mi
        storageClassName: manual
    - metadata:
        name: pgadmin-pgadmin4-volume
        labels:
          app: pgadmin-pgadmin4
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Ki
        storageClassName: manual
