# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# #it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-volume
  labels:
    app: postgres-data
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/data
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-conf-volume
  labels:
    app: postgres-conf
spec:
  capacity:
    storage: 100Ki
  accessModes: ["ReadOnlyMany"]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/postgresql.conf
    type: File

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-tablespace-volume
  labels:
    app: postgres-tablespace
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/tablespace
    type: Directory
